# Generated by Django 5.1 on 2024-10-15 13:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('new_post', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='newpost',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='new_post/media/uploads/'),
        ),
    ]
