# Generated by Django 5.1 on 2024-10-15 13:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('new_post', '0002_alter_newpost_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='newcomment',
            name='email',
            field=models.EmailField(max_length=254),
        ),
    ]
